### ISSUE TITLE
Mistake in berserk infantry "Increased squad size" option

### ISSUE THREAD

**Issue by Faspartato** [BSData/xenos-rampant#3]
In the Xenos Rampant manual it says the following:

•Increased Squad Size **(+1 point per unit)**: This unit begins the game with 10 Strength Points, and also increases its Attack Value to 3+. This unit’s Defence Value and Shoot Value remain unchanged.

In the roster, it adds 2 points instead

**Comment by DaeronAlagos** [comment]
Thank you for reporting this and nice spot 👍🏻 

I've also found the same issue on `Primative Infantry`. Will take me a bit longer than usual as I'll need to change the way the cost is attributed for all units. I'll get it fixed ASAP.

**Comment by Faspartato** [comment]
Thank you, James. It's really nice you're making this effort :)

**Comment by DaeronAlagos** [comment]
Fixed by 05dd6062ae63967c283e2740efbbf4f5913105d1

**Comment by Faspartato** [comment]
Great!
